name: Test artifact

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run creation script 
        run: echo "tata" > filename.txt
      - uses: actions/upload-artifact@v4
        with:
          name: filename
          path: filename.txt

  read:
    needs: [create]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: filename
      - name: read
        run: cat filename.txt
    
    
