name: Test artifact

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: run creation script 
        run: echo "toto" > filename.txt
      - uses: actions/upload-artifact@v4
        with:
          name: filename
          path: filename.txt
    
    
